# Generated by Django 4.2.11 on 2024-03-12 10:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='There is no title', max_length=255)),
                ('description', models.TextField(default='There is no description')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meetups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='There is no title', max_length=255)),
                ('description', models.TextField(default='There is no description')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('tags', models.CharField(default='none', max_length=255)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('invited', models.ManyToManyField(related_name='invited', to='YouthSpotsBrain.profile')),
                ('owner_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='YouthSpotsBrain.profile')),
                ('pin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YouthSpotsBrain.pins')),
            ],
        ),
    ]
