# Generated by Django 5.0.2 on 2024-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='pin_tags',
        ),
        migrations.AddField(
            model_name='pins',
            name='tags',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
