# Generated by Django 5.0.2 on 2024-03-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(default='There is no biography', max_length=2000),
        ),
    ]
