# Generated by Django 5.0.2 on 2024-03-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='pin_type',
            field=models.CharField(choices=[('user', 'User'), ('meetup', 'Meetup'), ('place', 'Place')], default='place', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(default='There is no biography', max_length=2000),
        ),
    ]
