# Generated by Django 4.2.11 on 2024-03-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetup', '0001_initial'),
        ('YouthSpotsBrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='meetups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetup.meetups'),
        ),
        migrations.AddField(
            model_name='pins',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='YouthSpotsBrain.tags'),
        ),
    ]
