# Generated by Django 5.0.2 on 2024-03-14 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('YouthSpotsBrain', '0001_initial'),
        ('meetup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='meetups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.meetups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_tags',
            field=models.ManyToManyField(related_name='favorite_tags', to='YouthSpotsBrain.tags'),
        ),
    ]
