# Generated by Django 5.0.2 on 2024-03-07 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='There is no description')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('owner_id', models.IntegerField(null=True)),
                ('invited', models.CharField(default='No one', max_length=255)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='pins',
            name='created_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pins',
            name='description',
            field=models.TextField(default='There is no description'),
        ),
        migrations.AddField(
            model_name='pins',
            name='invited',
            field=models.CharField(default='No one', max_length=255),
        ),
        migrations.AddField(
            model_name='pins',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pins',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pins',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pins',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pins',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
