# Generated by Django 4.2.11 on 2024-03-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0002_tags_profile_biography_profile_favorite_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YouthSpotsBrain.pins'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(default='There is no biography', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
