# Generated by Django 5.0.2 on 2024-03-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0002_tags_profile_biography_profile_favorite_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YouthSpotsBrain.pins'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
