# Generated by Django 5.0.2 on 2024-03-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0002_alter_profile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='pin_type',
            field=models.CharField(choices=[('user', 'User'), ('meetup', 'Meetup'), ('place', 'Place')], default='place', max_length=10),
        ),
    ]
