# Generated by Django 5.0.2 on 2024-03-08 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0002_meetup_data_meetup_userdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_meetup', models.CharField(max_length=30)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('type_meetup', models.CharField(choices=[('FC', 'Fan_cosplay'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FC', max_length=10)),
                ('location_meetup', models.BigIntegerField()),
                ('pins', models.BigIntegerField()),
                ('visibility', models.CharField(choices=[('+', 'Public'), ('#', 'Protected'), ('-', 'Private')], default='-', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupUserData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visibility', models.BooleanField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouthSpotsBrain.meetupdata')),
            ],
        ),
        migrations.DeleteModel(
            name='meetup_data',
        ),
        migrations.DeleteModel(
            name='meetup_userdata',
        ),
    ]
