# Generated by Django 5.0.2 on 2024-03-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0003_alter_meetups_pin_alter_tags_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('+', 'Public'), ('-', 'Private')], default='Private', max_length=10),
        ),
    ]
