# Generated by Django 4.2.11 on 2024-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0003_alter_meetups_pin_alter_profile_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='color',
            field=models.CharField(default='blue', max_length=255),
        ),
    ]
