# Generated by Django 5.0.2 on 2024-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0003_meetupdata_meetupuserdata_delete_meetup_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupuserdata',
            name='meeting_id',
        ),
        migrations.DeleteModel(
            name='MeetupData',
        ),
        migrations.DeleteModel(
            name='MeetupUserData',
        ),
    ]
