# Generated by Django 5.0.2 on 2024-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0003_pins_pin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='tags',
        ),
        migrations.AddField(
            model_name='pins',
            name='pin_tags',
            field=models.ManyToManyField(related_name='pin_tags', to='YouthSpotsBrain.tags'),
        ),
    ]
