# Generated by Django 5.0.2 on 2024-03-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0003_alter_meetups_pin_alter_profile_biography_and_more'),
        ('YouthSpotsBrain', '0004_meetups_visibility'),
    ]

    operations = [
    ]
