# Generated by Django 5.0.2 on 2024-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0004_remove_pins_tags_pins_pin_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='pin_tags',
        ),
        migrations.AddField(
            model_name='pins',
            name='tags',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
