# Generated by Django 5.0.2 on 2024-03-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0002_userauth'),
        ('YouthSpotsBrain', '0004_remove_pins_invited_remove_pins_owner_id_and_more'),
    ]

    operations = [
    ]
