# Generated by Django 4.2.11 on 2024-03-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0004_tags_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='tags',
        ),
        migrations.AddField(
            model_name='pins',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='YouthSpotsBrain.tags'),
        ),
    ]
