# Generated by Django 5.0.2 on 2024-03-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0004_remove_meetupuserdata_meeting_id_delete_meetupdata_and_more'),
        ('YouthSpotsBrain', '0005_merge_20240307_1707'),
    ]

    operations = [
    ]
