# Generated by Django 5.0.2 on 2024-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0005_merge_20240312_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('+', 'Public'), ('-', 'Private'), ('#', 'Protected')], default='Private', max_length=10),
        ),
    ]
