# Generated by Django 5.0.2 on 2024-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0006_alter_meetups_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='Private', max_length=10),
        ),
    ]
