# Generated by Django 5.0.2 on 2024-03-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0008_alter_meetups_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouthSpotsBrain.profile'),
        ),
    ]
