# Generated by Django 5.0.2 on 2024-03-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_meetup', models.CharField(max_length=30)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('type_meetup', models.CharField(choices=[('CE', 'Community Event'), ('SG', 'Social Gathering'), ('EE', 'Entertainment Event'), ('AC', 'Activity Club'), ('WC', 'Workshop/Class'), ('FE', 'Fitness Event'), ('VO', 'Volunteer Opportunity'), ('TE', 'Tech Event'), ('ME', 'Music Event'), ('DE', 'Dance Event')], default='CE', max_length=10)),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('meetup_location', models.BigIntegerField()),
                ('pins', models.BigIntegerField()),
                ('visibility', models.CharField(choices=[('+', 'Public'), ('#', 'Protected'), ('-', 'Private')], default='-', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupUserData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visibility', models.BooleanField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.meetupdata')),
            ],
        ),
    ]
