# Generated by Django 5.0.2 on 2024-03-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupdata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='meetupdata',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='meetupdata',
            name='meetup_location',
        ),
        migrations.RemoveField(
            model_name='meetupdata',
            name='pins',
        ),
    ]
