# Generated by Django 4.2.11 on 2024-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('+', 'Public'), ('-', 'Private'), ('#', 'Protected')], default='Private', max_length=10),
        ),
    ]
