# Generated by Django 4.2.11 on 2024-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_remove_meetupdata_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('ME', 'Music Event'), ('SG', 'Social Gathering'), ('EE', 'Entertainment Event'), ('TE', 'Tech Event'), ('WC', 'Workshop/Class'), ('AC', 'Activity Club'), ('FE', 'Fitness Event'), ('DE', 'Dance Event'), ('CE', 'Community Event'), ('VO', 'Volunteer Opportunity')], default='CE', max_length=10),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='-', max_length=10),
        ),
    ]
