# Generated by Django 5.0.2 on 2024-03-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0002_alter_profile_biography'),
        ('meetup', '0002_alter_meetups_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetups',
            options={'ordering': ['-created_timestamp']},
        ),
        migrations.AddField(
            model_name='meetups',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetups',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetups',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetups',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouthSpotsBrain.profile'),
        ),
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('-', 'Private'), ('#', 'Protected'), ('+', 'Public')], default='Private', max_length=10),
        ),
    ]
