# Generated by Django 5.0.2 on 2024-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouthSpotsBrain', '0002_remove_pins_pin_tags_pins_tags'),
        ('meetup', '0002_alter_meetups_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='invited',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited', to='YouthSpotsBrain.profile'),
        ),
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('-', 'Private'), ('#', 'Protected'), ('+', 'Public')], default='Private', max_length=10),
        ),
    ]
