# Generated by Django 5.0.2 on 2024-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_alter_meetups_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetups',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='meetups',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='Private', max_length=10),
        ),
    ]
