# Generated by Django 5.0.2 on 2024-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('DE', 'Dance Event'), ('FE', 'Fitness Event'), ('TE', 'Tech Event'), ('AC', 'Activity Club'), ('CE', 'Community Event'), ('EE', 'Entertainment Event'), ('SG', 'Social Gathering'), ('ME', 'Music Event'), ('WC', 'Workshop/Class'), ('VO', 'Volunteer Opportunity')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='-', max_length=10),
        ),
    ]
