# Generated by Django 5.0.2 on 2024-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('VO', 'Volunteer Opportunity'), ('EE', 'Entertainment Event'), ('FE', 'Fitness Event'), ('CE', 'Community Event'), ('TE', 'Tech Event'), ('ME', 'Music Event'), ('AC', 'Activity Club'), ('SG', 'Social Gathering'), ('WC', 'Workshop/Class'), ('DE', 'Dance Event')], default='CE', max_length=35),
        ),
    ]
