# Generated by Django 4.2.11 on 2024-03-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('VO', 'Volunteer Opportunity'), ('DE', 'Dance Event'), ('ME', 'Music Event'), ('SG', 'Social Gathering'), ('CE', 'Community Event'), ('FE', 'Fitness Event'), ('WC', 'Workshop/Class'), ('EE', 'Entertainment Event'), ('TE', 'Tech Event'), ('AC', 'Activity Club')], default='CE', max_length=10),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('-', 'Private'), ('+', 'Public'), ('#', 'Protected')], default='-', max_length=10),
        ),
    ]
