# Generated by Django 5.0.2 on 2024-03-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_alter_meetups_visibility'),
        ('meetup', '0005_alter_meetups_visibility'),
    ]

    operations = [
    ]
