# Generated by Django 5.0.2 on 2024-03-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_remove_meetups_latitude_remove_meetups_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('+', 'Public'), ('-', 'Private')], default='Private', max_length=10),
        ),
    ]
