# Generated by Django 5.0.2 on 2024-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_alter_meetups_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='name_meetup',
            field=models.CharField(max_length=255),
        ),
    ]
