# Generated by Django 5.0.2 on 2024-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('CE', 'Community Event'), ('VO', 'Volunteer Opportunity'), ('ME', 'Music Event'), ('SG', 'Social Gathering'), ('AC', 'Activity Club'), ('DE', 'Dance Event'), ('TE', 'Tech Event'), ('EE', 'Entertainment Event'), ('WC', 'Workshop/Class'), ('FE', 'Fitness Event')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('-', 'Private'), ('#', 'Protected'), ('+', 'Public')], default='Private', max_length=10),
        ),
    ]
