# Generated by Django 5.0.2 on 2024-03-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_alter_meetupdata_type_meetup'),
        ('meetup', '0006_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
    ]
