# Generated by Django 5.0.2 on 2024-03-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_merge_20240314_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='visibility',
            field=models.CharField(choices=[('+', 'Public'), ('#', 'Protected'), ('-', 'Private')], default='Private', max_length=10),
        ),
    ]
