# Generated by Django 4.2.11 on 2024-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('VO', 'Volunteer Opportunity'), ('ME', 'Music Event'), ('AC', 'Activity Club'), ('FE', 'Fitness Event'), ('DE', 'Dance Event'), ('CE', 'Community Event'), ('SG', 'Social Gathering'), ('EE', 'Entertainment Event'), ('TE', 'Tech Event'), ('WC', 'Workshop/Class')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('+', 'Public'), ('-', 'Private')], default='-', max_length=10),
        ),
    ]

