# Generated by Django 5.0.3 on 2024-03-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('CE', 'Community Event'), ('TE', 'Tech Event'), ('WC', 'Workshop/Class'), ('ME', 'Music Event'), ('AC', 'Activity Club'), ('EE', 'Entertainment Event'), ('DE', 'Dance Event'), ('SG', 'Social Gathering'), ('VO', 'Volunteer Opportunity'), ('FE', 'Fitness Event')], default='CE', max_length=35),
        ),
    ]
