# Generated by Django 5.0.2 on 2024-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_merge_20240312_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('DE', 'Dance Event'), ('CE', 'Community Event'), ('EE', 'Entertainment Event'), ('AC', 'Activity Club'), ('FE', 'Fitness Event'), ('TE', 'Tech Event'), ('VO', 'Volunteer Opportunity'), ('SG', 'Social Gathering'), ('WC', 'Workshop/Class'), ('ME', 'Music Event')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='-', max_length=10),
        ),
    ]
