# Generated by Django 5.0.3 on 2024-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_alter_meetupdata_type_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('AC', 'Activity Club'), ('CE', 'Community Event'), ('FE', 'Fitness Event'), ('SG', 'Social Gathering'), ('WC', 'Workshop/Class'), ('ME', 'Music Event'), ('DE', 'Dance Event'), ('EE', 'Entertainment Event'), ('TE', 'Tech Event'), ('VO', 'Volunteer Opportunity')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('-', 'Private'), ('#', 'Protected'), ('+', 'Public')], default='-', max_length=10),
        ),
    ]
