# Generated by Django 5.0.2 on 2024-03-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_alter_meetups_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetups',
            name='owner',
        ),
    ]
