# Generated by Django 4.2.11 on 2024-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('SG', 'Social Gathering'), ('WC', 'Workshop/Class'), ('DE', 'Dance Event'), ('VO', 'Volunteer Opportunity'), ('AC', 'Activity Club'), ('FE', 'Fitness Event'), ('CE', 'Community Event'), ('ME', 'Music Event'), ('EE', 'Entertainment Event'), ('TE', 'Tech Event')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='-', max_length=10),
        ),
    ]
