# Generated by Django 5.0.2 on 2024-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_alter_meetupdata_type_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('FE', 'Fitness Event'), ('AC', 'Activity Club'), ('VO', 'Volunteer Opportunity'), ('SG', 'Social Gathering'), ('CE', 'Community Event'), ('DE', 'Dance Event'), ('EE', 'Entertainment Event'), ('ME', 'Music Event'), ('TE', 'Tech Event'), ('WC', 'Workshop/Class')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('+', 'Public'), ('-', 'Private'), ('#', 'Protected')], default='Private', max_length=10),
        ),
    ]
