# Generated by Django 5.0.2 on 2024-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0010_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('EE', 'Entertainment Event'), ('DE', 'Dance Event'), ('WC', 'Workshop/Class'), ('SG', 'Social Gathering'), ('TE', 'Tech Event'), ('AC', 'Activity Club'), ('ME', 'Music Event'), ('VO', 'Volunteer Opportunity'), ('CE', 'Community Event'), ('FE', 'Fitness Event')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='Private', max_length=10),
        ),
    ]
