# Generated by Django 4.2.11 on 2024-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0012_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('CE', 'Community Event'), ('ME', 'Music Event'), ('WC', 'Workshop/Class'), ('AC', 'Activity Club'), ('EE', 'Entertainment Event'), ('TE', 'Tech Event'), ('SG', 'Social Gathering'), ('VO', 'Volunteer Opportunity'), ('DE', 'Dance Event'), ('FE', 'Fitness Event')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('+', 'Public'), ('-', 'Private')], default='-', max_length=10),
        ),
    ]
