# Generated by Django 5.0.2 on 2024-03-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_alter_meetupdata_type_meetup_and_more'),
        ('meetup', '0013_alter_meetupdata_type_meetup'),
    ]

    operations = [
    ]
