# Generated by Django 4.2.11 on 2024-03-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0013_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('TE', 'Tech Event'), ('FE', 'Fitness Event'), ('AC', 'Activity Club'), ('SG', 'Social Gathering'), ('EE', 'Entertainment Event'), ('CE', 'Community Event'), ('ME', 'Music Event'), ('VO', 'Volunteer Opportunity'), ('DE', 'Dance Event'), ('WC', 'Workshop/Class')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('+', 'Public'), ('#', 'Protected'), ('-', 'Private')], default='-', max_length=10),
        ),
    ]
