# Generated by Django 4.2.11 on 2024-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_alter_meetupdata_type_meetup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupdata',
            name='type_meetup',
            field=models.CharField(choices=[('FE', 'Fitness Event'), ('CE', 'Community Event'), ('VO', 'Volunteer Opportunity'), ('AC', 'Activity Club'), ('SG', 'Social Gathering'), ('DE', 'Dance Event'), ('TE', 'Tech Event'), ('WC', 'Workshop/Class'), ('ME', 'Music Event'), ('EE', 'Entertainment Event')], default='CE', max_length=35),
        ),
        migrations.AlterField(
            model_name='meetupdata',
            name='visibility',
            field=models.CharField(choices=[('#', 'Protected'), ('-', 'Private'), ('+', 'Public')], default='-', max_length=10),
        ),
    ]
